name: Coverage Testing

on: [workflow_dispatch, push, pull_request]

permissions: read-all

jobs:
  Coverage-on-Ubuntu:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Application
        run: |
          npm ci
          npm install -g c8
          npm exec install-firefox

      - name: Run Coverage Testing
        run: npm run coverage

      - name: Codecov
        if: ${{ github.event_name != 'pull_request' && env.CODECOV_TOKEN != '' }}
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}

  Testing-on-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Application
        run: |
          npm ci
          npm install -g c8
          npm exec install-firefox

      - name: Run Coverage Testing
        run: npm run coverage

  Testing-on-MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Application
        run: |
          npm ci
          npm install -g c8
          npm exec install-firefox

      - name: Run Coverage Testing
        run: npm run coverage